# Generated by Django 4.2.3 on 2023-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='building',
            name='curator',
            field=models.CharField(max_length=128, null=True, verbose_name='Куратор от ВДС'),
        ),
        migrations.AddField(
            model_name='building',
            name='executor',
            field=models.CharField(max_length=128, null=True, verbose_name='Исполнитель (Подрядчик)'),
        ),
        migrations.AddField(
            model_name='building',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания строительства'),
        ),
        migrations.AddField(
            model_name='building',
            name='gas_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер АЗС'),
        ),
        migrations.AddField(
            model_name='building',
            name='phone_executor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер исполнителя'),
        ),
        migrations.AddField(
            model_name='building',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала строительства'),
        ),
        migrations.AddField(
            model_name='building',
            name='warranty',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус гарантии 2 года'),
        ),
        migrations.AddField(
            model_name='building',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала гарантии'),
        ),
        migrations.AddField(
            model_name='building',
            name='warranty_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лет гарантии'),
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Название объекта'),
        ),
    ]
