# Generated by Django 4.2.3 on 2023-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128, null=True, verbose_name='Бренд')),
                ('banned_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Забаненый Telegram ID')),
                ('ban_status', models.BooleanField(default=False, null=True, verbose_name='Статус бана')),
                ('need_sorry', models.BooleanField(default=False, null=True, verbose_name='Нужно извиниться')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='mega_admin_status',
            field=models.BooleanField(default=False, verbose_name='Мега Админ'),
        ),
    ]
