# Generated by Django 4.2.3 on 2023-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banlist_myuser_mega_admin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banlist',
            name='brand',
        ),
    ]
