# Generated by Django 4.2.3 on 2023-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='name_reminder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название напоминания'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_reminder_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующего показа'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='owner_reminder_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='телеграм id создателя'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='чат id создания напоминания'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Интервал напоминания в минутах'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_last_view_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего показа'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status_reminder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус активности напоминания'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='text_reminder',
            field=models.CharField(blank=True, null=True, verbose_name='Текст напоминания'),
        ),
    ]
